import {
  Fingerprint,
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Image,
  Laptop,
  Loader2,
  MoreVertical,
  Pizza,
  Plus,
  Map,
  Settings,
  Sparkles,
  MoonStar,
  User,
  X,
  Sun,
  LogOut,
  Star,
  Info,
  Monitor,
  ArrowUpDown,
  CalendarDays,
  Eye,
  Trash2,
  CalendarPlus,
  Newspaper,
  Mail,
  BadgeDollarSign,
  SlidersHorizontal,
  LineChart,
  TrendingDown,
  TrendingUp,
  BarChart3,
  Users,
  UserPlus,
  MapPin,
  DollarSign,
  HelpingHand,
  Milestone,
  CircleDollarSign,
  UserMinus2,
  Edit,
  Upload,
  Phone,
  HandCoins,
  LayoutGrid,
  History,
} from "lucide-react";

export const Icons = {
  close: X,
  layoutGrid: LayoutGrid,
  dollarSign: DollarSign,
  handCoins: HandCoins,
  history: History,
  newspaper: Newspaper,
  phone: Phone,
  calendar: CalendarDays,
  spinner: Loader2,
  eye: Eye,
  chevronLeft: ChevronLeft,
  edit: Edit,
  fingerprint: Fingerprint,
  upload: Upload,
  chevronRight: ChevronRight,
  users: Users,
  arrowUpDown: ArrowUpDown,
  userPlus: UserPlus,
  mapPin: MapPin,
  currency: CircleDollarSign,
  helpingHand: HelpingHand,
  milestone: Milestone,
  userMinus: UserMinus2,
  media: Image,
  badgeDollarSign: BadgeDollarSign,
  trendingUp: TrendingUp,
  barChart3: BarChart3,
  trendingDown: TrendingDown,
  mail: Mail,
  logout: LogOut,
  settings: Settings,
  ellipsis: MoreVertical,
  add: Plus,
  trash: Trash2,
  monitor: Monitor,
  warning: AlertTriangle,
  sun: Sun,
  user: User,
  calendarPlus: CalendarPlus,
  arrowRight: ArrowRight,
  magic: Sparkles,
  pizza: Pizza,
  moonStar: MoonStar,
  laptop: Laptop,
  star: Star,
  map: Map,
  lineChart: LineChart,
  info: Info,
  slidersHorizontal: SlidersHorizontal,
  check: Check,
};
