import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Image,
  Laptop,
  Loader2,
  MoreVertical,
  Pizza,
  Plus,
  Map,
  Settings,
  Sparkles,
  MoonStar,
  User,
  X,
  Sun,
  PartyPopper,
  Waves,
  LogOut,
  Star,
  Info,
  Monitor,
  ArrowUpDown,
  CalendarDays,
  Eye,
  Trash2,
  CalendarPlus,
  PencilLine,
  SlidersHorizontal,
} from "lucide-react";

export const Icons = {
  logo: Waves,
  close: X,
  calendar: CalendarDays,
  spinner: Loader2,
  eye: Eye,
  edit: PencilLine,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowUpDown: ArrowUpDown,
  media: Image,
  logout: LogOut,
  settings: Settings,
  ellipsis: MoreVertical,
  add: Plus,
  trash: Trash2,
  monitor: Monitor,
  party: PartyPopper,
  warning: AlertTriangle,
  sun: Sun,
  user: User,
  calendarPlus: CalendarPlus,
  arrowRight: ArrowRight,
  magic: Sparkles,
  pizza: Pizza,
  moonStar: MoonStar,
  laptop: Laptop,
  star: Star,
  map: Map,
  info: Info,
  slidersHorizontal: SlidersHorizontal,
  check: Check,
};
